language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install -r dev-requirements.txt
script:
  # Primary test suite
  - inv test
  # Integration-level test suite (hard to reliably test full stack in-code :()
  - inv test -o --tests=integration
  # Docs sanity check
  - inv docs
