language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  #- "pypy3" # Looks like Sphinx (as of 1.4.1) is not pypy3 compat
install:
  - pip install -r dev-requirements.txt
matrix:
  # Only need to really test Sphinx 1.3 once, all combos is pointless.
  include:
    - python: 2.7
      env: SPHINX_13=true
script:
  # NOTE: this is the best-supported method for testing multiple dependency
  # versions right now, see
  # https://docs.travis-ci.com/user/languages/python/#Testing-Against-Multiple-Versions-of-Dependencies-(e.g.-Django-or-Flask)
  # NOTE: could strip out from dev-reqs.txt entirely, but what's the point?
  - "if [[ $SPHINX_13 == true ]]; then pip install 'sphinx<1.4'; fi"
  # Primary test suite
  - inv test
  # Integration-level test suite (hard to reliably test full stack in-code :()
  - inv test -o --tests=integration
  # Docs sanity check
  - inv docs
